server:
  port: 8003
spring:
  application:
    name: cache-service
  redis:
    database: 0
    ## Redis服务器地址
    host: 127.0.0.1
    password:
    ## Redis服务器连接端口
    port: 6379
    ## 连接超时时间（毫秒）
    timeout: 5000
    ## 连接池最大连接数（使用负值表示没有限制）
    pool:
      ax-active: 50
      ## 连接池最大阻塞等待时间（使用负值表示没有限制）
#      max-wait: 3000
#      ## 连接池中的最大空闲连接
#      max-idle: 20
#      ## 连接池中的最小空闲连接
#      min-idle: 2
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}