server:
  port: 9999

spring:
  application:
    name: api-gateway

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instanceId: ${spring.cloud.client.hostname}:${spring.application.name}:${spring.application.instance_id:${server.port}}

zuul:
  routes:
    user:
      path: /user/**
      serviceId: user-service
    activity:
      path: /activity/**
      serviceId: activity-service
    cache:
      path: /cache/**
      serviceId: cache-service
#  ignored-patterns: /user/info,/activity/info
